# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: server
    init: |
      apt-get update
      bundle install
    command: 
      bundle exec jekyll serve
  - name: hosting
    init: |
      npm install -g firebase-tools
# firebase login --no-localhost
# firebase deploy

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-browser
