# Overall title for pages.
title: "Macquarie University School of Computing Support for Marginalised Groups in Computing"

# Email address, no mailto:
email: "matthew.roberts@mq.edu.au"

# Files and directories that are not to be copied.
exclude:
  - .DSStore
  
theme: minimal-mistakes-jekyll
atom_feed:
  hide: true
head_scripts:
  - h5p_standalone/main.bundle.js

# Turn on built-in syntax highlighting.
highlighter: rogue

markdown: kramdown

kramdown:
  syntax_highlighter: rogue

defaults:
  - scope:
      path: ""
    values:
      layout: single
      sidebar:
        nav: "basic"
  - scope:
      path: "stage_5"
    values:
      layout: single
      sidebar:
        nav: "stage5"
  - scope:
      path: "stage_6"
    values:
      layout: single
      sidebar:
        nav: "stage6"
  - scope:
      path: "stage_7_undergraduate"
    values:
      layout: single
      sidebar:
        nav: "stage7"
  - scope:
      path: "stage_8_postgraduate"
    values:
      layout: single
      sidebar:
        nav: "stage8"
